1. read the sample csv file

In [ ]:
import numpy as np
import pandas as pd
data=pd.read_csv('/content/sample_data/california_housing_test.csv')
print(data)

      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0
1       -118.30     34.26                43.0       1510.0           310.0
2       -117.81     33.78                27.0       3589.0           507.0
3       -118.36     33.82                28.0         67.0            15.0
4       -119.67     36.33                19.0       1241.0           244.0
...         ...       ...                 ...          ...             ...
2995    -119.86     34.42                23.0       1450.0           642.0
2996    -118.14     34.06                27.0       5257.0          1082.0
2997    -119.70     36.30                10.0        956.0           201.0
2998    -117.12     34.10                40.0         96.0            14.0
2999    -119.63     34.42                42.0       1765.0           263.0

      population  households  median_income  median_house_value
0         1537.0       606.0         6.6085            344700.0
1          809.0       277.0         3.5990            176500.0
2         1484.0       495.0         5.7934            270500.0
3           49.0        11.0         6.1359            330000.0
4          850.0       237.0         2.9375             81700.0
...          ...         ...            ...                 ...
2995      1258.0       607.0         1.1790            225000.0
2996      3496.0      1036.0         3.3906            237200.0
2997       693.0       220.0         2.2895             62000.0
2998        46.0        14.0         3.2708            162500.0
2999       753.0       260.0         8.5608            500001.0

[3000 rows x 9 columns]

2.read the last 5 values of the csv file

In [ ]:
data.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

3. read first 5 values of the csv file

In [ ]:
data.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

4. read last 2 data from csv file

In [ ]:
data.tail(2)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

5. read only last 2 data from csv file

In [ ]:
data.head(2)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0

6. get the details of the csv sample csv file

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB

7. print the total number of rows and column in the csv file

In [ ]:
data.shape

(3000, 9)

In [ ]:
data=data.append(data)
data.shape

(6000, 9)

9. remove all the duplicates value from the csv file and print the total number of rows and column

In [ ]:
data=data.drop_duplicates()
data.shape

(3000, 9)

10. change the name of the column of the sample file

In [ ]:
col_names = ['long',
             'lat',
             'HMA',
             'TROOMS',
             'TBEDROOMS',
             'P',
             'HH',
             'MI',
             'MHV' ]
data=pd.read_csv('/content/sample_data/california_housing_test.csv', names=col_names)
print(data.head())

          long        lat                 HMA       TROOMS       TBEDROOMS  \
0    longitude   latitude  housing_median_age  total_rooms  total_bedrooms
1  -122.050000  37.370000           27.000000  3885.000000      661.000000
2  -118.300000  34.260000           43.000000  1510.000000      310.000000
3  -117.810000  33.780000           27.000000  3589.000000      507.000000
4  -118.360000  33.820000           28.000000    67.000000       15.000000

             P          HH             MI                 MHV
0   population  households  median_income  median_house_value
1  1537.000000  606.000000       6.608500       344700.000000
2   809.000000  277.000000       3.599000       176500.000000
3  1484.000000  495.000000       5.793400       270500.000000
4    49.000000   11.000000       6.135900       330000.000000

11. create a new csv file and write any 3 datqa into the csv file

In [ ]:
import pandas as pd
cities = pd.DataFrame([['Sacramento', 'California'], ['Miami', 'Florida']], columns=['City', 'State'])
cities.to_csv('cities.csv')
df = pd.read_csv('cities.csv')
print(df)

   Unnamed: 0        City       State
0           0  Sacramento  California
1           1       Miami     Florida

In [ ]:
import pandas as pd
cities = pd.DataFrame([['Sacramento', 'California'], ['Miami', 'Florida']], columns=['City', 'State'])
cities.to_csv('cities.csv', index=False)
df = pd.read_csv('cities.csv')
print(df)

         City       State
0  Sacramento  California
1       Miami     Florida

12. change the column name of the csv file created

In [ ]:
import pandas as pd
cities = pd.DataFrame([['Sacramento', 'California'], ['Miami', 'Florida']], columns=['City', 'State'])
new_column_names = ['City_Name', 'State_Name']
cities.to_csv('cities.csv', index=False, header=new_column_names)
df = pd.read_csv('cities.csv')
print(df)

    City_Name  State_Name
0  Sacramento  California
1       Miami     Florida

13. enter one unknown value to the csv file created

In [ ]:
import pandas as pd
cities = pd.DataFrame([['Sacramento', 'California'], ['Miami', 'Florida'], ['Washington DC', pd.NA]], columns=['City', 'State'])
cities.to_csv('cities.csv', index=False, na_rep='Unknown')
df = pd.read_csv('cities.csv')
print(df)

            City       State
0     Sacramento  California
1          Miami     Florida
2  Washington DC     Unknown

14. create a json file and write into json file

In [ ]:
import json
dictionary = {
    "name": "sathiyajith",
    "rollno": 56,
    "cgpa": 8.6,
    "phonenumber": "9976770500"
}
json_object = json.dumps(dictionary, indent=4)
with open("sample.json", "w") as outfile:
    outfile.write(json_object)

15. read the created json file

In [ ]:
import json
with open('sample.json', 'r') as openfile:
    json_object = json.load(openfile)
 
print(json_object)
print(type(json_object))

{'name': 'sathiyajith', 'rollno': 56, 'cgpa': 8.6, 'phonenumber': '9976770500'}
<class 'dict'>